### ISSUE TITLE
Allow pandas>=2

### ISSUE THREAD

**Issue by joe-pitt** [ICOS-Carbon-Portal/pylib#199]
After the upgrade to icoscp-0.2.1, pandas is now fixed to <2. This creates conflicts with lots of other stuff (e.g. openghg). Based on a quick scan I wonder whether this was done for stilt reasons? In any case when I manually upgrade to pandas-2.2.3 my openghg scripts using legacy functions to retrieve surface mole fraction data still work. So at the moment this is not an urgent fix for me, but it would be good to consider going forward.

**Comment by ZogopZ** [comment]
Hello @joe-pitt,

Thank you for your feedback. As you observed, we did indeed pin the version of pandas, but this action was not related to STILT. We did this to maintain some coherency with the ICOS JupyterHub, which is built using a Jupyter datascience notebook image that pins pandas to 1.3.5.

I appreciate you bringing this to our attention. Since the datascience notebook image is already pinning the pandas version, we can certainly relax the pandas dependencies for icoscp and icoscp_stilt going forward to pandas-2.2.3.

**Comment by ZogopZ** [comment]
Resolved via commits [15945e9](https://github.com/ICOS-Carbon-Portal/pylib/commit/15945e98099db932561db9ef996518f8e7bd2736) and [e3bd77a](https://github.com/ICOS-Carbon-Portal/pylib/commit/e3bd77a4ee6f74311efe29e08914736784978fa2).
Related releases: [icoscp 0.2.2](https://pypi.org/project/icoscp/) & [icoscp_stilt 0.1.3](https://pypi.org/project/icoscp_stilt/).

@joe-pitt
